version: '3.3'
services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    ports:
      - '5432:5432'
    expose:
      - '5432'
    container_name: 'postgresql'
    environment:
      - DB_USER=sa
      - DB_PASS=bilisimio
      - DB_NAME=movie

  movie:
    build:
      context: .
      dockerfile: Dockerfile.movie
    ports:
      - '8080:8080'
    links:
      - 'postgresql'
    depends_on:
      - 'postgresql'
    container_name: 'movie-service'
    deploy:
      mode: replicated
      replicas: 6

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
    links:
      - movie
