server:
  port: 8080
spring:
  application:
    name: movie-service
  datasource:
    initialize: true
    url: jdbc:postgresql://localhost:5432/movie
    username: sa
    password: bilisimio

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

flyway:
  enabled: true
  encoding: 'UTF-8'